DOMAIN_BRANCHES: dict[str, dict] = {
    "road-highway": {
        "label": "Roads & Highways",
        "multi_keywords": [
            "road construction", "road widening", "road improvement", "road rehabilitation",
            "highway widening", "highway construction", "highway improvement",
            "state highway", "national highway", "bituminous concrete",
            "bituminous macadam", "flexible pavement", "rigid pavement",
            "carriageway widening", "two laning", "four laning", "six laning",
            "culvert construction", "road over bridge", "grade separator",
            "bypass construction", "ring road", "expressway",
        ],
        "single_keywords": [
            "bituminous", "carriageway", "pavement", "embankment", "culvert",
            "subgrade", "granular", "WBM", "DBM", "SDBC", "BC", "GSB",
        ],
        "authoritative_signals": ["NHAI", "BBMP", "KSHIP", "KRDC", "NHDCL", "NHIDCL",
                                   "MORTH", "PWD", "RDPR", "BDA"],
    },
    "building-construction": {
        "label": "Buildings & Structures",
        "multi_keywords": [
            "building construction", "building works", "construction of building",
            "residential quarters", "staff quarters", "barracks construction",
            "school complex", "school building", "admin block", "administrative block",
            "institutional building", "hospital building", "office complex",
            "boundary wall", "internal roads and services", "water supply and sanitation",
            "civil and structural", "RCC framed structure",
        ],
        "single_keywords": [
            "barracks", "quarters", "dormitory", "hostel", "auditorium",
            "plinth", "superstructure", "masonry", "plastering", "flooring",
        ],
        "authoritative_signals": ["CPWD", "KVS", "NIT", "CRPF", "CISF", "BSF",
                                   "CPMF", "MES", "NHB", "NBCC"],
    },
    "irrigation-canal": {
        "label": "Irrigation & Canals",
        "multi_keywords": [
            "canal desilting", "canal lining", "canal improvement", "canal rehabilitation",
            "irrigation canal", "irrigation channel", "branch canal", "distributary canal",
            "lift irrigation", "command area", "head regulator", "cross regulator",
            "hydraulic structures", "dam construction", "reservoir construction",
            "water supply scheme", "rural water supply",
        ],
        "single_keywords": [
            "desilting", "desiltation", "canal", "weir", "barrage",
            "anicut", "sluice", "offtake", "distributary", "minors",
        ],
        "authoritative_signals": ["CNNL", "KNNL", "CWC", "IWAI", "NABARD",
                                   "WRD", "Cauvery Neeravari", "Tungabhadra"],
    },
    "bridge-structures": {
        "label": "Bridges & Structures",
        "multi_keywords": [
            "bridge construction", "major bridge", "minor bridge",
            "road over bridge", "fly over", "elevated corridor",
            "abutment construction", "pier construction", "deck slab",
            "prestressed concrete", "steel bridge", "girder bridge",
            "viaduct construction", "retaining wall",
        ],
        "single_keywords": [
            "abutment", "pier", "girder", "viaduct", "pylon",
            "span", "superstructure", "substructure", "bearing",
        ],
        "authoritative_signals": ["NHAI", "NHIDCL", "BRO", "NBCC"],
    },
    "railway-metro": {
        "label": "Railway & Metro",
        "multi_keywords": [
            "road over bridge", "rail over bridge", "railway bridge",
            "railway track", "track laying", "track doubling", "track renewal",
            "station building", "railway station", "platform construction",
            "rail doubling", "gauge conversion", "metro rail",
            "suburban railway", "dedicated freight corridor",
        ],
        "single_keywords": [
            "railway", "rail", "ROB", "LHS", "RHS", "ballast",
            "sleeper", "turnout", "signalling", "traction",
        ],
        "authoritative_signals": ["RVNL", "Rail Vikas Nigam", "DMRC", "KMRL", "BMRCL",
                                   "Indian Railways", "Railway Board", "South Western Railway",
                                   "South Central Railway", "Western Railway", "Central Railway",
                                   "Eastern Railway", "Northern Railway"],
    },
    "lift-escalator": {
        "label": "Lifts & Escalators",
        "multi_keywords": [
            "lift maintenance", "elevator maintenance", "lift AMC",
            "annual maintenance contract", "lift installation", "elevator installation",
            "escalator maintenance", "escalator installation",
            "OEM authorized", "manufacturer authorized", "authorized service provider",
        ],
        "single_keywords": [
            "lift", "elevator", "escalator", "hoist", "dumbwaiter",
        ],
        "authoritative_signals": ["Otis", "Schindler", "KONE", "Mitsubishi", "ThyssenKrupp"],
    },
    "it-digitization": {
        "label": "IT & Digitization",
        "multi_keywords": [
            "digitization of records", "library digitization", "document scanning",
            "document digitization", "archival scanning", "microfilm scanning",
            "software development", "application development", "IT infrastructure",
            "data center", "network infrastructure", "ERP implementation",
            "OCR processing", "metadata creation", "digital preservation",
            "pages scanned", "book digitization",
        ],
        "single_keywords": [
            "digitization", "scanning", "OCR", "metadata", "archival",
            "software", "database", "server", "networking", "cybersecurity",
        ],
        "authoritative_signals": ["NIC", "MeitY", "NeGD", "BECIL", "STPI"],
    },
    "communication-networking": {
        "label": "Communication & Networking",
        "multi_keywords": [
            "communication infrastructure", "optical fiber cable", "fiber optic",
            "BTS tower", "mobile tower", "telecom infrastructure",
            "CCTV surveillance", "surveillance system", "security system",
            "public address system", "intercom system",
            "last mile connectivity", "broadband network",
        ],
        "single_keywords": [
            "fiber", "OFC", "CCTV", "telecom", "BTS", "antenna",
            "repeater", "switch", "router", "bandwidth",
        ],
        "authoritative_signals": ["BSNL", "BBNL", "TRAI", "DoT", "NIC"],
    },
}

SECTOR_TO_BRANCH: dict[str, str] = {
    "road-construction": "road-highway",
    "road construction": "road-highway",
    "highway": "road-highway",
    "roads": "road-highway",
    "building-construction": "building-construction",
    "building construction": "building-construction",
    "civil construction": "building-construction",
    "canal-works": "irrigation-canal",
    "canal works": "irrigation-canal",
    "irrigation": "irrigation-canal",
    "bridge-construction": "bridge-structures",
    "bridge construction": "bridge-structures",
    "railway-works": "railway-metro",
    "railway works": "railway-metro",
    "metro": "railway-metro",
    "lift-maintenance": "lift-escalator",
    "lift maintenance": "lift-escalator",
    "elevator": "lift-escalator",
    "it-services": "it-digitization",
    "it services": "it-digitization",
    "digitization": "it-digitization",
    "communication": "communication-networking",
    "networking": "communication-networking",
    "telecom": "communication-networking",
}
